### PR TITLE
Ricochet rework

### PR DESCRIPTION
**Pull request by thegrb93**
Not tested yet, but has a lot of fixes to ricochet math. Probably requires tuning of some variables. @noth1ng1996 can you test it?

### CODE REVIEW

**Comment by Bubbus** [comment]
This looks promising, thanks for the effort.  

Once it's tested and you feel confident in it then let me know.  I'll do my own quick testing pass on it then and merge it for you if it looks good.  If there's issues I'll work with you to get them sorted out.

**Comment by noth1ng1996** [comment]
It is still not quite right, because at angles close to 90 there is still non-zero probability of no ricochet. What I expected to see was addition of two variables, which defined value of angles with 0% and 100% ricochet probability. Impact angle less than first value would result in no ricochet, anything larger than second - ricochet. Probability distribution between these two values does not play huge role, so using simple uniform distribution would give acceptable result. Also "armor breach" is yet to be implemented.

**Comment by thegrb93** [comment]
There is no definition of those limits you are talking about.

Besides it's more realistic to provide that tiny probability of it not ricochet.

I tested this and it works for me. Just need tuning.

**Comment by Bubbus** [comment]
I think something like this is what's on the table?:

ricos

Using arbitrary numbers: If the shell comes in at 45 degrees, there's basically no chance of a bounce (I'd definitely be in awe of it happening).  Between that and 60 degrees, you have an increasing scale of bounce chance (we're in the region here of maybe-will maybe-won't).  After that, we're in ricochet town and any successful hits would be incredibly surprising.

The example numbers above (45 and 60) would be affected by things like momentum, shell diameter, whatever relevant attributes make sense here.  There might be some literature out there on the topic of what affects bounces.

**Comment by thegrb93** [comment]
A sigmoid describes that pretty well.

**Comment by thegrb93** [comment]
Here's an example http://www.wolframalpha.com/input/?i=1%2F(1%2Be%5E(-(x+-+60)%2F4))+x%3D-20+to+120

**Comment by Bubbus** [comment]
That looks pretty good - I'll leave the rest to you, let me know when it's ready to go.

**Comment by thegrb93** [comment]
@noth1ng1996 I've updated the code to better do what you described. Mind testing now?

**Comment by thegrb93** [comment]
I disagree with points 1. and 2.; realistically there should be a tiny chance of it. I've seen videos of .50 cal ricochets bouncing off a rock back to the shooter. That chance is infinitesimal with the sigmoid so I think that is currently fine. 

I think I need you to do the tuning with respect to armor and ammo type. I'm not familiar enough at all with ACF to balance it correctly, but I think you can.

**Comment by Bubbus** [comment]
IIRC there exist ACF servers which implement overmatching in their custom code.  From what I heard, if the caliber of the round exceeds some fraction of the armour thickness then it will never ricochet, solving the "paper deflector" issue.

I assume something like sectional density would be a more realistic measure but caliber-based has the benefit of being intuitive to the end-user, which is also valuable.  For example if we set the fraction to 0.5, then I immediately know I need >50mm of armour to cause ricochets vs 100mm cannons.

**Comment by thegrb93** [comment]
Read this article if you still don't believe a .50 cal can have a backwards ricochet off of 1/4" plate. http://madogre.com/?p=1090

**Comment by noth1ng1996** [comment]
I was thinking about reworking penetration/ricochet mechanics and came up with next pseudo code:
```
if PenetrationProbability() > math.rand() then
	-- Penetration
	-- Round.Penetration = Round.Penetration - LOSArmor
	-- Entity.Health = Entity.Health - PenetrationDamage
elseif BreachProbability() > math.rand() then
	-- BreachProbability
	-- Round.Penetration = Round.Penetration - Armor
	-- Entity.Health = Entity.Health - BreachDamage
else
	if RicochetProbability() > math.rand() then
		-- Ricochet
	else
		-- Round destruction
	end
end
```
Where PenetrationProbability():
penetration probability
Approx.: _y = 10.198 / (1 + e^-(92.2985 * (x - 1))_

BreachProbability():
breach probability

RicochetProbability() - same as proposed by **thegrb93**, with adjusted Bullet.Ricochet values.

What do you think? In my opinion, it provides decent approximation of how penetration and ricochet happen in real-life, while keeping penetrations and ricochets relatively predictable and reasonable, fixing layering abuse and possibly making pancake designs to use thicker armor.
I'm not sure if this can completely break compatibility with addons (for ex. ACF Missiles). It may also cause problems with HEAT and HE. They have implicit penetration values (~10mm for 100mm HE shell) but I'm not sure if they "can" penetrate, in which case this ability should be added, but again I'm not sure if it will break compatibility.
It also might be required to buff armor penetration for all rounds (~5 - 10%) to compensate for randomization or completely ditch it (it requires testing).

**Comment by thegrb93** [comment]
That looks good. I'll try that

**Comment by noth1ng1996** [comment]
I made mistake in code. Check for breach should be done before penetration.

**Comment by thegrb93** [comment]
Question. What's the difference between breach and penetration again?

**Comment by noth1ng1996** [comment]
https://wiki.warthunder.com/index.php?title=Damage_mechanics#Breach_.2F_Overmatch_.2F_Stamping

**Comment by Bubbus** [comment]
WRT the passing missiles query, ACF Missiles piggybacks onto default ACF mechanics and will survive just fine through this change.

**Comment by Bubbus** [comment]
Hi @thegrb93,

I've just merged in some very similar changes in pull-req #269.

I've assumed that you and @noth1ng1996 worked together on these changes and attributed you both in the changelog file.  If there's any ground left uncovered after this then please feel free to make another pull-req with further changes.  Always happy to accept help.

As always, I'm grateful for every contribution that comes in - this is no exception.  Thanks.

**Pull request closed without merging**
