### PR TITLE
Fix gearbox brake and added torque limit to prevent crashing/spontanious deletion

### PR DESCRIPTION
**Pull request by thegrb93**
The brake code made no sense previously. Also too much torque causes the wheel to either get deleted or crash the server.

### CODE REVIEW

**Comment by thegrb93** [comment]
Haven't tested the newest commit. Will do soon.

**Comment by thegrb93** [comment]
Went ahead and optimized all the worldToLocal/localToWorld that could be simplified to worldToLocalVector/localToWorldVector

**Comment by Bubbus** [comment]
Looks good, thanks for the effort.

Once you've tested it out properly let me know and I'll merge it in.

**Comment by thegrb93** [comment]
@Bubbus tested and working well

**Comment by Bubbus** [comment]
Great, I'm away this weekend but I'll merge this when I get back (I need to increase the version number in the globals file and add credits to the readme/changelog).  Remind me here if I haven't done this by Monday.

**Comment by thegrb93** [comment]
@Bubbus

**Comment by Bubbus** [comment]
Thanks, merging.

**Pull request merged**
