### PR TITLE
Update sv_acfballistics.lua

### PR DESCRIPTION
**Pull request by monkstick**
Remove Debris, doors and ragdols for now, until a better solution is found.  If we just return end, then people can use debris to armor there tanks.

### CODE REVIEW

**Comment by thegrb93** [comment]
You should use a table, and you don't need tostring around ent:GetClass() afaik.
```
local ignored_entities = {
func_door = true,
func_door_rotating = true,
prop_ragdoll = true
}
...
if ignored_entities[ent:GetClass()] then
...
end

```

**Comment by Fervidusletum** [comment]
Instead of removing said entities, better to add the ent to the bullets filter, and retry the trace.  Doors should be left alone, since it would affect normal doors around the map.

**Comment by monkstick** [comment]
That sounds fine.  Where is the blacklist for bullets?  I remove doors too for now,  because my combat map has 4 massive garage doors.  When someone misses a shot, we get the lag issue.

**Comment by Fervidusletum** [comment]
I'll fix the issue at the source once I can track it down, as this solution introduces other problems.

**Pull request closed without merging**
