### PR TITLE
Errors? Whats that?

### PR DESCRIPTION
**Pull request by EgrOnWire**
Check for Bullet validity. Or die with errors otherwise.

### CODE REVIEW

**Comment by brandonsturgeon** [comment]
@nrlulz pls merge this

**Comment by SpiralP** [comment]
This is already fixed at https://github.com/nrlulz/ACF/blob/351cc3e1e358df8144d5b2a181edf100ae1f30c0/lua/effects/acf_bulleteffect/init.lua#L111
for some reason github doesn't update

**Comment by brandonsturgeon** [comment]
Cool. This one can be closed, then.

**Comment by Bubbus** [comment]
Merged in @vMajx's version of this at https://github.com/nrlulz/ACF/pull/244.  Apologies for the delay.

**Pull request closed without merging**
