### PR TITLE
fixes for #225

### LINKED ISSUE #225: console script error on bullet impact
```
[ERROR] addons/acf/lua/effects/acf_bulleteffect/init.lua:111: attempt to index local 'Bullet' (a nil value)
  1. unknown - addons/acf/lua/effects/acf_bulleteffect/init.lua:111
```

This seems to appear when bullets impact the world. Any ideas?

### PR DESCRIPTION
**Pull request by MechWipf**
This should fix #225

It seems that CLuaEmitter:Finish() does not cleanup the userdata of the object, which causes further errors even when checking for `Bullet and Bullet.Tracer`.

### CODE REVIEW

**Comment by Bubbus** [comment]
A good change.  The correct way to check entity validity is using `IsValid()` which returns false for NULL entities as well as nil values.

Your changes combined with that function would make this effect fairly bulletproof (badum-tish)

```if Bullet and IsValid(Bullet.Tracer) then Bullet.Tracer:Finish() end```

**Comment by MechWipf** [comment]
Okay, I replaced all `nil` checks with `IsValid()` checks and tested it. This looks more clean than setting the `Bullet.Tracer` to `nil`.

**Comment by EgrOnWire** [comment]
When will those be merged with main branch?

**Comment by MechWipf** [comment]
It runs stable on my server. So it should be ready to be merged.

**Comment by Bubbus** [comment]
@Fervidusletum ?!

**Comment by EgrOnWire** [comment]
Its been 10 days since the fixes were provided, why not merge them now?

**Comment by brandonsturgeon** [comment]
... or now?

**Comment by Bubbus** [comment]
Just returned from a long hiatus.  Catching up on pull-requests, merged in @vMajx's version of this at #244. 
 Thanks for the work and apologies for the delay.

**Comment by brandonsturgeon** [comment]
Yay! Thank you @Bubbus !!

**Comment by georgeravenholm** [comment]
maybe we could thank maj aswell :^)

**Comment by vMajx** [comment]
:^)

**Comment by Bubbus** [comment]
https://github.com/nrlulz/ACF/commit/f568b3ba5357e99fbdb37f0fdff346b3e4cd0fac#diff-e8800259c4985f4a73b0936128034c53R172 

thank u :^)

**Comment by brandonsturgeon** [comment]
:^)

**Pull request closed without merging**
