### PR TITLE
Fix StarfallEx ACF functions, added recent new E2 functions

### PR DESCRIPTION
**Pull request by CheezusChrust**
StarfallEx ACF functions now work properly (old ones didn't work at all), also added some of the functions that were recently added to Expression 2.

### CODE REVIEW

**Comment by TheWizardLizard** [comment]
Any reason this hasn't been merged yet?

**Comment by thegrb93** [comment]
Idk, author left gmod maybe. Make a new fork if you wanna maintain it. I certainly don't care enough for ACF to do so.

**Comment by thegrb93** [comment]
Look at network https://github.com/nrlulz/ACF/network to see who's maintaining the best.

**Comment by TheWizardLizard** [comment]
Plenty of other pullrequests get merged though, @Amplar merged a killicons fix not even 24 days ago, (when this was posted) and these functions work flawlessly.

**Comment by thegrb93** [comment]
@TheWizardLizard he probably nagged him on steam about it or something.

**Comment by thegrb93** [comment]
heres a missing one


	-- Returns the muzzle velocity of the ammo in a crate or gun
	function ents_methods:acfDragCoef()
		SF.CheckType( self, ents_metatable )
		local this = unwrap( self )

		if not isAmmo( this ) or isGun( this ) then return 0 end
		if restrictInfo( SF.instance.player, this ) then return 0 end
		return ( this.BulletData[ "DragCoef" ] or 0 ) / ACF.DragDiv
	end

**Pull request merged**
