### PR TITLE
Fix the Starfall ACF functions

### PR DESCRIPTION
**Pull request by CheezusChrust**

### CODE REVIEW

**Comment by thegrb93** [comment]
One last think is to put everything in a `SF.addHook("postload", function() ... end)` so that load order won't be an issue.

**Comment by CheezusChrust** [comment]
When you say everything, do you mean the entire contents of the file, or just a particular section of it? I'm new to Starfall libraries so I'm not sure how some things work.

**Comment by thegrb93** [comment]
Everything in the file yea

**Comment by CheezusChrust** [comment]
Would it also be possible to also have these functions do the highlighting that the regular entity methods have? Where you can type, for example, E:setAngles( ... ) and setAngles gets highlighted. Messed around for a bit and can't seem to get that to happen, unsure if that's just how library extensions behave or if there's a fix for that.

**Pull request closed without merging**
